DECLARE
task_id NUMBER;
aw_name VARCHAR2(2000) := 'EDF_NHH_OUTPUT_AW.EDF_NHH_OUTPUT';
BEGIN
  FINANCE.PKG_TASK_MANAGER.CREATETASK(aw_name,'Re Run of Energy Wholesale View EXEC DML Step 6 of Proces Task 13792',task_id,'S22157');
  --FINANCE.PKG_TASK_MANAGER.ADDSTEP_RUN_SQL(task_id,'BEGIN pkg_gmf_pre_process.sp_ins_gdf_small_sc (''G10019''); COMMIT; END;');
  FINANCE.PKG_TASK_MANAGER.AddStep_Run_DML(task_id,'NHH_OUTPUT_SC_GSP_BMU_SC(NHH_OUTPUT_SC ''N10089'') =''B10005''',aw_name,NULL);
  FINANCE.PKG_TASK_MANAGER.AddStep_Run_DML(task_id,'NHH_OUTPUT_SC_PUBLISHED(NHH_OUTPUT_SC ''N10089'') =''Y''',aw_name,NULL);
  FINANCE.PKG_TASK_MANAGER.AddStep_Run_DML(task_id,'NHH_OUTPUT_SC_energy_wholesale_pub(NHH_OUTPUT_SC ''N10089'') =''Y''',aw_name,NULL);
  FINANCE.PKG_TASK_MANAGER.ADDSTEP_AWCOMMIT(task_id);
  FINANCE.PKG_TASK_MANAGER.ENQUEUETASK(task_id);
END;  

