DECLARE
task_id NUMBER;
aw_name VARCHAR2(2000) := 'GDF_AW.GDF';
BEGIN
  FINANCE.PKG_TASK_MANAGER.CREATETASK(aw_name,'Delete minicube GDF_SMALL_10069',task_id,'C10879');
  FINANCE.PKG_TASK_MANAGER.ADDSTEP_RUN_SQL(task_id,'BEGIN FINANCE.Submit_cube_delete_job(''GDF_AW.GDF'',''GDF_SMALL_10069'',FALSE); END;');
  FINANCE.PKG_TASK_MANAGER.ENQUEUETASK(task_id);
END;  
